@echo off
echo Starting Up Minecraft Java Edition...
PING -n 6 127.0.0.1>nul
call java\bin\java.exe -jar minecraft.jar
echo Minecraft Java Edition Has Been Started. Exiting...
PING -n 6 127.0.0.1>nul
